### PR TITLE
Update welcome.blade.php

### PR DESCRIPTION
**Pull request by josephxtian**
Complete rewrite of the welcome email, updating to the current practises of the space.

### CODE REVIEW

**Review by chris18890 — APPROVED** [review]

**Review by rjackson — COMMENTED** [review]
I think this looks good overall. I've noted one small possible issue below with one of the links from the e-mail.

The HTML overall is pretty solid – very good for a first attempt at writing HTML! There were some existing issues with the old HTML though, where we could have done with some more `p` or paragraph tags to break the content up a bit (we have loose text flying around, which isn't _technically_ proper).

I want to test this email on my local copy of the site before we progress this to the live website, to minimise the risk of breaking something on live. The e-mail side of our local development environment doesn't seem to be working properly at the moment though.

If everybody's okay holding off on this for a moment, I'll come back to this in the evening to sort the local development email issues, trigger this e-mail locally so I can preview it exactly as it would be sent by the membership system, and maybe do a quick tidy up of the HTML (again, addressing pre-existing issues)

**Review by rjackson — APPROVED** [review]
Managed to get this tested :) Turns out the welcome e-mail is only send _after_ somebody sets up their direct debit, not the moment they register.

I've fixed the link in the e-mails footer and done a quick tidy up of the HTML, and I'm happy to approve this :)

I'll give the others a chance to review my tweaks before progressing merging this and getting it live

**Comment by rjackson** [comment]
Merged & deployed. @josephxtian These changes will now be live for new members, and sent as soon as they've set up their direct debit.

**Comment by josephxtian** [comment]
Thanks Rob!

**Pull request merged**
