### PR TITLE
Creates the welding room and welding team

### PR DESCRIPTION
**Pull request by diazwatson**

### CODE REVIEW

**Comment by diazwatson** [comment]
@rjackson @conorriches guys could you please take a look at this PR when you can?
Also, should I populate the tools for the welding area programatically?

**Review by conorriches — COMMENTED** [review]
Nice one - looks good! Was the addition of a blank room on the form intentional and discussed btw?

**Comment by diazwatson** [comment]
Intentional but no discussed 🙈

I did it because when I added the welding room I noticed that the drop down shows the first option as default.

Another option would be to replace the empty room for something like "Select one". I think that would make more sense.

**Comment by conorriches** [comment]
> Intentional but no discussed 🙈
> 
> I did it because when I added the welding room I noticed that the drop down shows the first option as default.
> 
> Another option would be to replace the empty room for something like "Select one". I think that would make more sense.

Ah good shout! I haven't tested this but does a blank entry allow you to add the tool anyway? I'm thinking it should ideally prevent you adding a tool if it's not got a room specified?

**Comment by diazwatson** [comment]
Yeap, it does 👇
Screenshot 2024-02-05 at 08 23 23

**Review by conorriches — APPROVED** [review]

**Review by chris18890 — APPROVED** [review]

**Comment by diazwatson** [comment]
Thanks guys 👍
I will now need someone to add my member user to the "welding role" to be able to add and manage tools in it.

**Comment by chris18890** [comment]
think that'll be a director/someone with admin permissions? @rjackson @peterdroberts @harvy4002

**Comment by harvy4002** [comment]
I assume there's no hurry for this but @rjackson drop me a DM if you start working on it, so we don't double work. I mean this is all documented and easy to deploy... right? RIGHT?!?!?

**Comment by diazwatson** [comment]
Happy to help (if needed) setting up CI/CD for this or any other hackspace web project...

...when the new welding area is 100% up and running

**Comment by rjackson** [comment]
Deployed & added @diazwatson and Mike to the welding team.

**Comment by diazwatson** [comment]
Although I don't see the option to add equipment so cannot add the welding machine.
Is that restricted to only members of the equipment team? 
Should I pass the info to one of them for them to created it for me?

Also, out of curiosity, how you added Mike to the welding team without removing him from metalwork if the `role_user` table only accept one id? 🤔

**Comment by diazwatson** [comment]
Was thinking this morning. I could also add the tools programmatically 🤔

Please let me know if that's better

**Pull request merged**
